---
title: "Predicting Manga Scores"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Prerequisites

```{r, message=FALSE}
# load libraries
library(tidyverse)
library(tidymodels)
library(patchwork)
library(ggrepel)
library(vip)

# set theme for plots
theme_set(theme_bw())

# load data
manga_raw <- read_csv("data/manga.csv")
```

```{r}
manga <- manga_raw %>%
  drop_na(score) %>%
  filter(status %in% c("currently_publishing", "finished")) %>%
  select(title, score, type, status, start_date, end_date, members, 
         favorites, sfw, genres, themes, demographics, serializations) %>%
  drop_na()
```

```{r}
# fills in empty strings in a vector
replace_empty_string <- function(.str) {
  ifelse(.str == "", "Other or NA", .str)
}

# returns a dataframe with the mean score of each unique value in a given category
get_mean_scores <- function(df, category) {
  mean_scores <- df %>%
    # remove square brackets
    mutate(cleaned_category = str_remove(!!sym(category), "\\["),
           cleaned_category = str_remove(cleaned_category, "\\]")) %>%
    # separate column into multiple rows for each unique value in the category column
    separate_rows(cleaned_category, sep = ",") %>% 
    # remove apostrophes and whitespace
    mutate(cleaned_category = str_remove(cleaned_category, "\\'"),
           cleaned_category = str_remove(cleaned_category, "\\'"),
           cleaned_category = str_trim(cleaned_category)) %>%
    # replace missing values with filler
    mutate_at("cleaned_category", ~ replace_empty_string(.x)) %>%
    # get mean score for each category
    group_by(cleaned_category) %>%
    summarise(score = mean(score)) %>%
    # sort from highest to lowest
    arrange(desc(score))
  
  # save dataframe as CSV file
  file_name <- str_glue("data/manga_mean_scores_{category}.csv")
  write_csv(mean_scores, file_name)
  
  # return dataframe
  return(mean_scores)
}
```

## Genres

```{r}
get_mean_scores(manga, "genres")
```

## Themes

```{r}
get_mean_scores(manga, "themes")
```

## Studios

```{r}
get_mean_scores(manga, "genres")
```

## Demographics

```{r}
get_mean_scores(manga, "demographics")
```

## Serializations

```{r}
get_mean_scores(manga, "serializations")
```

## Calculate scores

```{r, message=FALSE}
# calculate overall median score
total_mean_score <- manga %>% 
  pull(score) %>% 
  median()

# example: maps something like categories = ['category1', 'category2'] to a mean score
category_mean_score <- function(categories, df_map, replace_empty = total_mean_score) {
  # get mapped values
  category <- df_map %>% pull(1)
  score <- df_map %>% pull(2)
  
  # use overall median score if input is empty
  if (categories == "[]") {
    return(replace_empty)
  }
  
  # otherwise, calculate the mean score over those categories
  else {
    mean_score <- categories %>%
      # remove brackets and single quotes
      str_remove("\\[") %>%
      str_remove("\\]") %>%
      str_remove_all("\\'") %>%
      # split at commas
      strsplit(split = ", ") %>%
      unlist() %>%
      # map each category to a score and calculate the mean
      plyr::mapvalues(from = category, 
                      to = score,
                      warn_missing = FALSE) %>%
      as.numeric() %>%
      mean()
    
    return(mean_score)
  }
}

# load dataframes with mean scores 
mean_scores_genres <- read_csv("data/manga_mean_scores_genres.csv")
mean_scores_themes <- read_csv("data/manga_mean_scores_themes.csv")
mean_scores_demographics <- read_csv("data/manga_mean_scores_demographics.csv")
mean_scores_serializations <- read_csv("data/manga_mean_scores_serializations.csv")

manga_clean <- manga %>%
  # get mean scores for multi-label columns
  mutate(genres_score = map_dbl(genres, ~ category_mean_score(.x, mean_scores_genres)),
         themes_score = map_dbl(themes, ~ category_mean_score(.x, mean_scores_themes)),
         demographics_score = map_dbl(demographics, ~ category_mean_score(.x, mean_scores_demographics)),
         serializations_score = map_dbl(serializations, ~ category_mean_score(.x, mean_scores_serializations))) %>%
  # remove old columns
  select(-c(genres, themes, demographics, serializations))

# save as CSV file
write_csv(manga_clean, "data/manga_clean.csv")
```

# Exploratory data analysis {.tabset}

```{r}
# load cleaned data
manga_clean <- read_csv("data/manga_clean.csv")
manga_clean
```

## MAL scores

```{r}
# histogram
p1 <- manga_clean %>%
  ggplot(aes(x = score)) +
  geom_histogram(bins = 50) +
  labs(title = "Histogram of MAL scores")

# boxplot
p2 <- manga_clean %>%
  ggplot(aes(x = score)) +
  geom_boxplot() +
  labs(title = "Boxplot of MAL scores")

# combine plots
p1 + p2 + plot_layout(ncol = 1)
```

```{r}
# correlation plot for numeric variables
anime_clean %>%
  select_if(is.numeric) %>%
  cor() %>%
  corrplot::corrplot(method = "number")
```

```{r, message=FALSE}
manga_clean %>%
  # convert to wide format
  select(contains("score")) %>%
  pivot_longer(cols = contains("_score"),
               names_to = "type",
               values_to = "type_score") %>%
  # scatter plot + smoothing
  ggplot(aes(x = type_score, y = score)) +
  geom_point() +
  geom_smooth() +
  facet_wrap(~ type, nrow = 2) +
  # update labels
  labs(title = "MAL scores vs. derived mean scores",
       x = "Derived mean score",
       y = "MAL score")
```
